services:

  disaster_insurance:
    build: .
    image: aviatorifeanyi/disaster_insurance:v1
    container_name: disaster_insurance
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: disaster_db
    volumes:
      - .:/app
    networks:
      - disaster
    command: ['python', 'main.py']

  postgres:
    image: postgres:16.9
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: disaster_insurance
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data
    networks:
      - disaster

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: pgadmin
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - disaster

volumes:
  postgres_data:

networks:
  disaster:

